sudo: required
language: node_js
dist: trusty
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
  - npm install -g npm
  - npm --version
deploy:
  skip_cleanup: true
  provider: npm
  email: sharma02gaurav@gmail.com
  api_key:
    secure: i9K+oMtEwAQ52HwEWE+Dc54tb2A69DAUQOgOVx06vwbdwBnTDIdTQBPhb6crf2O1JRsUlP5uyl1+QmkihLcKkOHYQ9TFBwOfmcDR4nUil0ZAVJ1Di+EwK00MCtXFUfnoEujaeubse14yMwG8VZpIUZC/snyYGFWOCWONpaKOTHhlzLXjq4fW94FScKy4VJd7xsizfqf+kT9jv1Mf0IG8YlxnGznQTbuibWcS1TI47lS5UdsJEyInBvB3XJ8X9F8RkTWhTUYx96Ow9BYaDK7P+BXOTp1W3mp9iR+rKPaZA3VJCZ34SNqcUgguYUiIlTNaQ3L6Poxwrq93JzVC3zgueJdxLsWyz9Rm0e0hq+ezFbz6DOgH80ybC+SvaDG1+msxhUJ+2FPJzPtzfsz+IWDEYvCnvFke/Q100wo+q/KTtxsOxks+LnXvxIoBAO7aFu3fnWeHLkpGIwY4JjvDZ373AkTQA7vjBVXxr2NHsnfiXCb0IGtbrqxB3zmvrUn/41r7VRMPZDq2KXDI4JNnw90s4D/is8Ck73MY+Nwp3P9CCPMm3ApO59GM+UyeUlE/Wayn5nLz5XAwqC8c6GPhGVtXi/hfpT4x+K3NQfAWBkF8XoKSNO8CJ+bu0Dn21pXRvTq3NuhxdOs2dsla8gq0nIY6luvEOm/BuyPFW123BdGfK6w=
